- name: Add some security rules to the firewall
  hosts: PaloAltoFirewalls
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Grab the credentials from ansible-vault
    include_vars: 'firewall-secrets.yml'
    no_log: 'no'

  - name: Add test rule 1 to the firewall
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'add'
      rule_name: 'Ansible test 1'
      description: 'An Ansible test rule'
      source_zone: ['internal']
      destination_zone: ['external']
      source_ip: ['host-1.2.3.4']
      source_user: ['any']
      destination_ip: ['any']
      category: ['any']
      application: ['any']
      service: ['service-xyz']
      hip_profiles: ['any']
      action: 'allow'

  - name: Add test rule 2 to the firewall
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'add'
      rule_name: 'Ansible test 2'
      description: 'Another Ansible test rule'
      source_zone: ['internal']
      source_ip: ['range-192.168.100.100-200']
      source_user: ['any']
      hip_profiles: ['any']
      destination_zone: ['external']
      destination_ip: ['any']
      category: ['any']
      application: ['any']
      service: ['service-abc']
      action: 'allow'
      group_profile: 'default'

  - name: Add test rule 3 to the firewall
    panos_security_rule:
      ip_address: '{{ ip_address }}'
      username: '{{ username }}'
      password: '{{ password }}'
      operation: 'add'
      rule_name: 'Ansible test 3'
      description: 'Yet another Ansible test rule'
      source_zone: ['internal']
      source_ip: ['net-10.0.0.0-8']
      source_user: ['any']
      hip_profiles: ['any']
      destination_zone: ['external']
      destination_ip: ['any']
      category: ['any']
      application: ['any']
      service: ['test-service-group']
      action: 'allow'
