- name: Restart firewall
  hosts: PaloAltoFirewalls
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Restart panos device
    panos_restart:
      ip_address: hosts
      password: "admin"
