- name: Restart firewall
  hosts: PA-test
  connection: local
  gather_facts: False

  roles:
    - role: PaloAltoNetworks.paloaltonetworks

  tasks:
  - name: Restart panos device
    panos_restart:
      ip_address: "{{ ip_address }}"
      username: admin
      password: admin
